### PR TITLE
Scheduled grain distribution for week ending September 27th, 2020, opt-ins

### PR DESCRIPTION
**Pull request by s-ben**
This PR opts in three new contributors (Lozadaluis12, Gala, reuptaken) and distributes $2,500 worth of DAI for the week ending September 27th, 2020. 

@decentralion, couldn't use the [auto-generated PR](https://github.com/sourcecred/makerdao-cred/pull/17) this week because I didn't opt in the new participants until after it was generated.

### CODE REVIEW

**Comment by decentralion** [comment]
Can we pass this to panchovillage to review?

**Comment by decentralion** [comment]
Edit: I'm happy to review too, but let's use this as an opportunity to onboard miguel to reviewing instance changes.

**Comment by s-ben** [comment]
@decentralion good idea, though I still get nervous myself and feel more comfortable after you review. My process currently is basically just eyeballing the numbers to see if they're about what I expect, verifying that any opt-ins show up. It might be better if there was a little more comprehensive "checklist" or verification process. E.g. currently, the ledger isn't really human readable, is there a way to make it more so? Or read it with machines (code)? 

If you're comfortable with current process though so am I, and I think we can get panchovillage up to speed pretty quick.

**Review by decentralion — APPROVED** [review]
Yeah, that's really fair. We need to build better tools for reviewing these PRs.

My process is to skim the JSON data, and compare it to my knowledge of what should be happening. I recognize that isn't something that you or @panchomiguel can reasonably do. Let's start asking @topocount, @hammadj, and @befitsandpiper to help review PRs like this.

Once we build a proper ledger UI, it'll be far easier to inspect these changes without being a dev.

With respect to this PR, the commit history is wonky. It looks like you have an alternate version of 10961baafb8856cc27213339fbad2bd8c09efb04 in your stack for some reason, and then you merged (which happened very cleanly since the two commits were the same except for the hash), and then you aplied your changes. You can avoid this if you always start from a clean branch off master when you are making the commit, i.e.

```
git fetch
git checkout origin/master
git checkout -b distro_0928
```
After that, things look fine.

Another suggestion: process opt-ins every Friday. That will be a simpler process that will be easier to review. Then we can just let the automated system do the Grain distribution.

**Comment by s-ben** [comment]
@decentralion cool, gotta up my git game...

Was going to start processing opt-ins on Fri or Sat this week actually, but forgot. Added a few extra reminders to my Gcal, now in unavoidable mode. Will also sync up with @panchomiguel this week and make sure he's got everything he needs to process opt-ins, review payouts.

**Pull request merged**
